### ISSUE TITLE
Cloud we create wechaty-getting-start repo for Rust users?

### ISSUE THREAD

**Issue by huan** [wechaty/rust-wechaty#10]
For other Polyglot Wechaty, we have https://github.com/wechaty/python-wechaty-getting-started/, https://github.com/wechaty/go-wechaty-getting-started/, etc, which great helps the new users with the specific language to start using Wechaty faster.

Could our Rust Wechaty also create a **rust-wechaty-getting-started** repo, so that a new user can:

1. clone the repo
2. `make install`
3. `make bot`

to run our `ding-dong-bot.rs`?

**Comment by lucifer1004** [comment]
To do that, we need to publish our packages on crates.io first.

**Comment by lucifer1004** [comment]
The starter repo has been created as https://github.com/wechaty/rust-wechaty-getting-started

**Comment by huan** [comment]
Awesome, congratulations!
