### ISSUE TITLE
Package names

### ISSUE THREAD

**Issue by lucifer1004** [wechaty/rust-wechaty#11]
Due to my fault, I published a package named `wechaty_puppet` before, so we could not publish `wechaty-puppet` due to crates.io's constraints.

I'd like to hear your opinions on the package names.

## Plan A: Use snake case

- `filebox`
- `wechaty`
- `wechaty_puppet`
- `wechaty_puppet_mock`
- `wechaty_puppet_service`

A shortcoming here is that I named the auto generated grpc package `wechaty-grpc`, so `wechaty_grpc` is not allowed. We will have to consider an alternative name for the grpc package, if we want to keep a uniform naming convention.

## Plan B: Use kebal case

- `filebox`
- `wechaty`
- `wechaty-puppet-container` / `wechaty-puppet-wrapper` / `wechaty-puppet-abstract` (or even maybe simply `puppet`, since it is not taken yet)
- `wechaty-puppet-mock`
- `wechaty-puppet-service`
- `wechaty-grpc`

**Comment by lucifer1004** [comment]
This is a prerequisite for #10 since the getting-started would need published packages.

**Comment by huan** [comment]
I'd like to suggest that we use kebal case (plan b) to be consistent with Node NPM package names if possible.

And my another two cents:

1. the FileBox module name in NPM is `file-box`, 
2. I think we can use the name `wechaty_puppet` as well because it will be an internal dependencies.

**Comment by lucifer1004** [comment]
Closed via #14
