### ISSUE TITLE
Create a logo image for Rust Wechaty

### ISSUE THREAD

**Issue by huan** [wechaty/rust-wechaty#16]
It will be great to have a Rust + Wechaty logo for our project, just like other Polyglot Wechaty projects!

The easiest way is just to merge the Rust logo with the Wechaty logo, which is exactly what we did before.

**Comment by lucifer1004** [comment]
I have proposed one in the Polyglot WeChat group.

**Comment by lucifer1004** [comment]
![rust-wechaty-logo](https://user-images.githubusercontent.com/13583761/108784634-cd0cf280-75aa-11eb-9094-f973918afc94.png)

**Comment by huan** [comment]
What a cute logo, love it!

> [Ferris the Rustacean 🦀](https://rustacean.net/)

**Comment by huan** [comment]
We can put the image to `docs/images/` in the repo, and then use markdown `![](docs/images/rust-wechaty.png)` to display it in README

**Comment by lucifer1004** [comment]
Closed via #19
