### ISSUE TITLE
To keep all the commits in the new repo

### ISSUE THREAD

**Issue by huan** [wechaty/rust-wechaty#9]
We have some history commits in this repo.

If we want to keep the history commits, we can use the  **Transfer ownership** feature in _Settings_ to transfer this repo to Wechaty org.

> Transfer ownership  
> Transfer this repository to another user or to an organization where you have the ability to create repositories.

**Comment by huan** [comment]
Duplicated with https://github.com/lucifer1004/rust-wechaty-monorepo/issues/1

**Comment by lucifer1004** [comment]
I made a new repo instead of keeping the history commits because there are many temporary commits and some commits cannot compile, which I do not want to include in this repo.

**Comment by huan** [comment]
Ok, got it.

So I understand that it's on purpose. :ok_hand:
